//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("eMoney Insight")]
[assembly: AssemblyCompany("Insight Module")]
[assembly: AssemblyProduct("Insight")]
[assembly: AssemblyCopyright("Copyright © Jon Wagner, used by permission")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.12.34")]
[assembly: AssemblyFileVersion("1.0.12.34")]


