using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Insight.Database.Sample
{
	/// <summary>
	/// Defines a repository interface.
	/// </summary>
	/// <remarks>Generated by InsightRepository.snippet. Extend this with methods in a separate partial interface.</remarks>
    partial interface IBeerRepository
	{
        #region Single Sync CRUD Methods
		/// <summary>
		/// Selects a single Beer from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>The selected Beer.</returns>
		Beer SelectBeer(int id);

		/// <summary>
		/// Inserts a single Beer into the repository.
		/// </summary>
		/// <param name="beer">The Beer to insert.</param>
		void InsertBeer(Beer beer);

		/// <summary>
		/// Updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to update.</param>
		void UpdateBeer(Beer beer);

		/// <summary>
		/// Upserts a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to upsert.</param>
		void UpsertBeer(Beer beer);

		/// <summary>
		/// Deletes a Beer in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		void DeleteBeer(int id);
        #endregion

        #region Multiple Sync CRUD Methods
		/// <summary>
		/// Selects multiple Beers from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>The selected Beer.</returns>
		IList<Beer> SelectBeers(IEnumerable<int> id);

		/// <summary>
		/// Inserts multiple Beers into the repository.
		/// </summary>
		/// <param name="beer">The Beers to insert.</param>
		void InsertBeers(IEnumerable<Beer> beer);

		/// <summary>
		/// Updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to update.</param>
		void UpdateBeers(IEnumerable<Beer> beer);

		/// <summary>
		/// Upserts multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to upsert.</param>
		void UpsertBeers(IEnumerable<Beer> beer);

		/// <summary>
		/// Deletes multiple Beers in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		void DeleteBeers(IEnumerable<int> id);
        #endregion

        #region Find Sync Methods
		/// <summary>
		/// Finds Beers matching a filter object.
		/// </summary>
		/// <param name="filter">The filter to use.</param>
		/// <returns>The selected Beers.</returns>
        IList<Beer> FindBeers(object filter);
        #endregion

        #region Single Async CRUD Methods
		/// <summary>
		/// Asynchronously selects a single Beer from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>A task returning the selected Beer.</returns>
		Task<Beer> SelectBeerAsync(int id);

		/// <summary>
		/// Asynchronously Inserts a single Beer into the repository.
		/// </summary>
		/// <param name="beer">The Beer to insert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task InsertBeerAsync(Beer beer);

		/// <summary>
		/// Asynchronously updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to update.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task UpdateBeerAsync(Beer beer);

		/// <summary>
		/// Asynchronously updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to upsert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task UpsertBeerAsync(Beer beer);

		/// <summary>
		/// Asynchronously deletes a Beer in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task DeleteBeerAsync(int id);
        #endregion

        #region Multiple Async CRUD Methods
		/// <summary>
		/// Asynchronously selects multiple Beers from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>A task returning the selected Beers.</returns>
		Task<IList<Beer>> SelectBeersAsync(IEnumerable<int> id);

		/// <summary>
		/// Asynchronously Inserts multiple Beers into the repository.
		/// </summary>
		/// <param name="beer">The Beers to insert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task InsertBeersAsync(IEnumerable<Beer> beer);

		/// <summary>
		/// Asynchronously updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to update.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task UpdateBeersAsync(IEnumerable<Beer> beer);

		/// <summary>
		/// Asynchronously updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to upsert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task UpsertBeersAsync(IEnumerable<Beer> beer);

		/// <summary>
		/// Asynchronously deletes multiple Beers in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		Task DeleteBeersAsync(IEnumerable<int> id);
        #endregion

        #region Find Async Methods
		/// <summary>
		/// Asynchronously finds Beers matching a filter object.
		/// </summary>
		/// <param name="filter">The filter to use.</param>
		/// <returns>The selected Beer.</returns>
        Task<IList<Beer>> FindBeersAsync(object filter);
        #endregion
	}

	/// <summary>
	/// Implements a repository interface.
	/// </summary>
	/// <remarks>Generated by InsightRepository.snippet. Extend this with methods in a separate partial interface.</remarks>
	partial class BeerRepository : IBeerRepository
	{
		/// <summary>
		/// The factory function used to generate a new connection 
		/// for the repository when it needs to perform a database operation.
		/// </summary>
		private Func<System.Data.IDbConnection> _connectionFactory;

        #region Constructors
		/// <summary>
		/// Initializes a new instance of the BeerRepository class.
		/// </summary>
		/// <param name="connectionFactory">
		/// A factory function that generates a new connection 
		/// for the repository when it needs to perform a database operation.
		/// </param>
		public BeerRepository(Func<System.Data.IDbConnection> connectionFactory)
		{
			_connectionFactory = connectionFactory;
		}
        #endregion

        #region Single Sync CRUD Methods
		/// <summary>
		/// Selects a single Beer from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>The selected Beer.</returns>
		public Beer SelectBeer(int id)
		{
			return _connectionFactory().Query<Beer>("SelectBeer", new { id = id }).FirstOrDefault();
		}

		/// <summary>
		/// Inserts a single Beer into the repository.
		/// </summary>
		/// <param name="beer">The Beer to insert.</param>
		public void InsertBeer(Beer beer)
		{
			_connectionFactory().Insert("InsertBeer", beer);
		}

		/// <summary>
		/// Updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to update.</param>
		public void UpdateBeer(Beer beer)
		{
			_connectionFactory().Execute("UpdateBeer", beer);
		}

		/// <summary>
		/// Upserts a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to update.</param>
		public void UpsertBeer(Beer beer)
		{
			_connectionFactory().Insert("UpsertBeer", beer);
		}

		/// <summary>
		/// Deletes a Beer in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		public void DeleteBeer(int id)
		{
			_connectionFactory().Execute("DeleteBeer", new { id = id });
		}
        #endregion

        #region Multiple Sync CRUD Methods
		/// <summary>
		/// Selects multiple Beers from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>The selected Beer.</returns>
		public IList<Beer> SelectBeers(IEnumerable<int> id)
        {
            return _connectionFactory().Query<Beer>("SelectBeers", id);
        }

		/// <summary>
		/// Inserts multiple Beers into the repository.
		/// </summary>
		/// <param name="beer">The Beers to insert.</param>
		public void InsertBeers(IEnumerable<Beer> beer)
		{
			_connectionFactory().InsertList("InsertBeers", beer);
		}

		/// <summary>
		/// Updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to update.</param>
		public void UpdateBeers(IEnumerable<Beer> beer)
		{
			_connectionFactory().Execute("UpdateBeers", beer);
		}

		/// <summary>
		/// Upserts multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to upsert.</param>
		public void UpsertBeers(IEnumerable<Beer> beer)
		{
			_connectionFactory().InsertList("UpsertBeers", beer);
		}

		/// <summary>
		/// Deletes multiple Beers in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		public void DeleteBeers(IEnumerable<int> id)
		{
			_connectionFactory().Execute("DeleteBeers", new { id = id });
		}
        #endregion

        #region Find Sync Methods
		/// <summary>
		/// Finds Beers matching a filter object.
		/// </summary>
		/// <param name="filter">The filter to use.</param>
		/// <returns>The selected Beers.</returns>
        public IList<Beer> FindBeers(object filter)
        {
            return _connectionFactory().Query<Beer>("FindBeers", filter);
        }
        #endregion

        #region Single Async CRUD Methods
		/// <summary>
		/// Asynchronously selects a single Beer from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>A task returning the selected Beer.</returns>
		public Task<Beer> SelectBeerAsync(int id)
		{
			return _connectionFactory().QueryAsync<Beer>("SelectBeer", new { id = id }).ContinueWith(t => t.Result.FirstOrDefault());
		}

		/// <summary>
		/// Asynchronously Inserts a single Beer into the repository.
		/// </summary>
		/// <param name="beer">The Beer to insert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task InsertBeerAsync(Beer beer)
		{
			return _connectionFactory().InsertAsync("InsertBeer", beer);
		}

		/// <summary>
		/// Asynchronously updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to update.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task UpdateBeerAsync(Beer beer)
		{
			return _connectionFactory().ExecuteAsync("UpdateBeer", beer);
		}

		/// <summary>
		/// Asynchronously updates a single Beer in the repository.
		/// </summary>
		/// <param name="beer">The Beer to upsert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task UpsertBeerAsync(Beer beer)
		{
			return _connectionFactory().InsertAsync("UpsertBeer", beer);
		}

		/// <summary>
		/// Asynchronously deletes a Beer in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beer.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task DeleteBeerAsync(int id)
		{
			return _connectionFactory().ExecuteAsync("DeleteBeer", new { id = id });
		}
        #endregion

        #region Multiple Async CRUD Methods
		/// <summary>
		/// Asynchronously selects multiple Beers from the repository by identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>A task returning the selected Beers.</returns>
		public Task<IList<Beer>> SelectBeersAsync(IEnumerable<int> id)
		{
			return _connectionFactory().QueryAsync<Beer>("SelectBeers", id);
		}

		/// <summary>
		/// Asynchronously Inserts multiple Beers into the repository.
		/// </summary>
		/// <param name="beer">The Beers to insert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task InsertBeersAsync(IEnumerable<Beer> beer)
		{
			return _connectionFactory().InsertListAsync("InsertBeers", beer);
		}

		/// <summary>
		/// Asynchronously updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to update.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task UpdateBeersAsync(IEnumerable<Beer> beer)
		{
			return _connectionFactory().ExecuteAsync("UpdateBeers", beer);
		}

		/// <summary>
		/// Asynchronously updates multiple Beers in the repository.
		/// </summary>
		/// <param name="beer">The Beers to upsert.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task UpsertBeersAsync(IEnumerable<Beer> beer)
		{
			return _connectionFactory().InsertListAsync("UpsertBeers", beer);
		}

		/// <summary>
		/// Asynchronously deletes multiple Beers in the repository matching the given identifier.
		/// </summary>
		/// <param name="id">The id of the Beers.</param>
		/// <returns>A task representing the completion of the operation.</returns>
		public Task DeleteBeersAsync(IEnumerable<int> id)
 		{
			return _connectionFactory().ExecuteAsync("DeleteBeers", id);
		}
        #endregion

        #region Find Async Methods
		/// <summary>
		/// Asynchronously finds Beers matching a filter object.
		/// </summary>
		/// <param name="filter">The filter to use.</param>
		/// <returns>The selected Beers.</returns>
        public Task<IList<Beer>> FindBeersAsync(object filter)
        {
            return _connectionFactory().QueryAsync<Beer>("FindBeers", filter);
        }
        #endregion
	}
}