//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

[assembly: AssemblyCopyright("Copyright © Jon Wagner, used by permission")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Insight.Database.Providers.Default, PublicKey=00240000048000009400000006020000002400005253413100040000010001006d47703dd0ace847c1cddc4cd240d64c8060b287b756927841cba67ab0480425e9a8d12c7d91a73bd9368aee6d81e3c8fa89f92d8020fe2b8b938271f40d866d6a4a9615858c3692b6a0dd3e6b672df0b15e4715dede56b9e29307644c4fbfa09ffdc76bb055dbb40e7d412c7a61980f92e680fdd88e425778ca0a96e2322a92")]
